sudo: true
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem install bundler -v 1.12.5
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh -s -- --channel=nightly
  - bundle && bundle exec rake build_lib
script: bundle exec rake
